In [14]:
#### Shallow COPY
import copy

# Original list
original_list = [1, 2, [3, 4]]

# Create a shallow copy
shallow_copied_list = copy.copy(original_list)

# Modifying the shallow copy
shallow_copied_list[0] = 10  # This change will not affect the original list
shallow_copied_list[2][0] = 30  # This change will affect the original list

print("Original List:", original_list)  # Output: [1, 2, [30, 4]]
print("Shallow Copied List:", shallow_copied_list)  # Output: [10, 2, [30, 4]]


Original List: [1, 2, [30, 4]]
Shallow Copied List: [10, 2, [30, 4]]


In [18]:
#### View
# Original list
original_list = [1, 2, 3, 4]

# Creating a view using slicing
view_list = original_list[1:3]  # This creates a new list that references the elements

# Modifying the view
view_list[0] = 10  # This change will not affect the original list

# Modifying the original list
original_list[1] = 20  # This change will affect the view

print("Original List:", original_list)  # Output: [1, 20, 3, 4]
print("View List:", view_list)  # Output: [3] (the view does not reflect the change in the original)


Original List: [1, 2, 3, 4]
View List: [10, 3]


In [ ]:
#### Deep copy

# Original list
original_list = [1, 2, [3, 4]]

# Create a deep copy
deep_copied_list = copy.deepcopy(original_list)

# Modifying the deep copy
deep_copied_list[0] = 10  # This change will not affect the original list
deep_copied_list[2][0] = 30  # This change will not affect the original list

print("Original List:", original_list)  # Output: [1, 2, [3, 4]]
print("Deep Copied List:", deep_copied_list)  # Output: [10, 2, [30, 4]]


In [22]:
import numpy as np

# Create a NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a shallow copy 
shallow_copied_array = original_array

original_array[0,0] = 100 #This change will affect the shallow_copied array

# Modify the shallow copy
shallow_copied_array[0, 0] = 10  # This change will affect the original array

print("Original Array:\n", original_array)
print("Shallow Copied Array:\n", shallow_copied_array)


Original Array:
 [[100   2   3]
 [  4   5   6]]
Shallow Copied Array:
 [[100   2   3]
 [  4   5   6]]


In [12]:
# Create a NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a view using slicing
view_array = original_array[0, :]  # This creates a view of the first row

# Modify the view
view_array[0] = 10  # This change will affect the original array

print("Original Array:\n", original_array)
print("View Array:\n", view_array)


Original Array:
 [[10  2  3]
 [ 4  5  6]]
View Array:
 [10  2  3]


In [24]:
import numpy as np

# Create a NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a deep copy
deep_copied_array = original_array.copy()

# Modify the deep copy
deep_copied_array[0, 0] = 10  # This change will not affect the original array

print("Original Array:\n", original_array)
print("Deep Copied Array:\n", deep_copied_array)


Original Array:
 [[1 2 3]
 [4 5 6]]
Deep Copied Array:
 [[10  2  3]
 [ 4  5  6]]
